### ISSUE TITLE
Save button?

### ISSUE THREAD

**Issue by ghost** [veggiedefender/hn-friends#1]
It wasn't clear to me whether the tag name autosaves or if I was supposed to type the name before clicking "add friend". Could be helpful to have an explicit save button. Just an idea. Not sure how many other people feel the same as me.

**Comment by veggiedefender** [comment]
This makes sense. Where should I place the button?

**Comment by ghost** [comment]
To the right of the textbox could work.

**Comment by veggiedefender** [comment]
What do you think of this? I'll do more testing to make sure I didn't break anything, and if you like it, it'll be part of the next release.

![2018-08-08_14 45 45](https://user-images.githubusercontent.com/8890878/43857531-8e9fb0e6-9b19-11e8-9555-0ba9e50d2e82.png)

**Comment by ghost** [comment]
Personally I like it :) but that's just me, I could be an outlier.

**Comment by veggiedefender** [comment]
This will appear in [release 1.1](https://github.com/veggiedefender/hn-friends/releases/tag/v1.1) and should be available to download in a few minutes/hours.
